### ISSUE TITLE
数据清洗交付

### ISSUE THREAD

**Issue by icepy** [Antalpha-Labs/ledger#6]
- 所有的脚本放置在 `scripts/elleria` 中（需要自己创建 `elleria` 目录）
- 可以按区块高度来同步增量
- 在 `scripts/elleria` 中且有一个 README.md，描述用户该如何使用和运行脚本，要有明确的步骤（中英文两版）
- 在 `scripts/leancloud` 目录中（需要自己创建 `leancloud` 目录）提供 `leancloud` 按月查询的脚本
   -  例如：输入 start 2022-11-01 00:00 end 2022-12-01 00:00 可将 11 月的统计数据查询出来
- 在 docs 目录中创建一个工作说明文档，描述工作量，时间评估的表格

**Comment by TecSong** [comment]
| 工作拆分        | 内容说明                                                                                                                                                                  | 工时（hour） |
|-------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------|
| 前期准备        | 主要包括：1.需求理解、确认（如收益界定、跑全量地址还是单个地址、抽成比例获取等等）2.开发环境准备（依赖安装、测试开发用的provider url、leancloud账号与api key） 3.leancloud学习                                                         | 4        |
| 解决方案调研      | "主要包括：1.通过检索transaction是否能满足需求：不能（主流provider服务商都不支持内部交易的获取）2.检索event log是否满足需求（能拿到交易详情）3.收入/支出如何判断（因为仅从event中无法判断，需要从input中参数来判断）4.其他字段如何获取，如交易hash、 区块号等 5.数据清洗总体流程" | 12       |
| 数据清洗代码编写、自测 | "主要包括：1.ELM swap合约相关逻辑实现（包括input 解析）2.nft swap合约相关逻辑实现（包括input 解析）3.World Boss(magic transfer)相关逻辑实现（包括input 解析）4.数据格式化及存储到leancloud逻辑实现 5.测试与验证、bug修复等"              | 32       |
| API查询脚本     | 支持按照地址、时间范围等进行查询（利用leancloud sdk）                                                                                                                                     | 4        |
| 后期交付        | "主要包括：数据清洗脚本wiki文档等成果交接、其他" | 4        ||             |                                                                                                                                                                       |          |
|             | 总计                                                                                                                                                                    | 64       |

**Comment by TecSong** [comment]
TRC20 : TUmK8HTbqEdBXPH2b1XZd64dnST9ozjq4R

**Comment by icepy** [comment]
拨款 2672 USDT 

https://tronscan.org/#/transaction/a330fb4362f6d4538c23397c358f7325fb5e5d25b02977c1a9ffdd3023466cf7
